apiVersion: apps/v1
kind: Deployment
metadata:
  name: aceest-fitness
  labels:
    app: aceest-fitness
    strategy: rolling
spec:
  replicas: 2
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: aceest-fitness
      strategy: rolling
  template:
    metadata:
      labels:
        app: aceest-fitness
        strategy: rolling
    spec:
      containers:
        - name: aceest-fitness
          image: docker.io/library/devops-assignment-2:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 20
